import { setTimeout as delay } from "timers/promises"

const smokeTag = `codex-api-smoke-${Date.now()}`
const port = Number(process.env.API_PORT) || 3101

process.env.LLM_PROVIDER = "mock"
process.env.API_PORT = String(port)
process.env.TELEGRAM_TOKEN = ""

const { initializeDb, queryOne, run } = await import("../infra/db/pool.js")
const { startApiServer, stopApiServer } = await import("../interface/api/server.js")

initializeDb()
const server = startApiServer({ port, hostname: "127.0.0.1" })

try {
  await waitForHealth(port)

  const response = await fetch(`http://127.0.0.1:${port}/api/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: smokeTag, page: "smoke-api" }),
  })

  if (!response.ok) {
    throw new Error(`chat failed: ${response.status} ${await response.text()}`)
  }

  const body = await response.json() as { reply?: string; eventId?: string }
  if (!body.eventId) throw new Error("chat response missing eventId")
  if (!body.reply?.includes(smokeTag)) throw new Error(`mock reply missing smoke tag: ${body.reply}`)

  await waitForMemoryPatch(smokeTag)
  await verifyStatus(port)
  console.log("api smoke ok")
} finally {
  cleanupSmokeRows(smokeTag)
  await stopApiServer(server)
}

async function verifyStatus(portNumber: number): Promise<void> {
  const response = await fetch(`http://127.0.0.1:${portNumber}/api/status`)
  if (!response.ok) throw new Error(`status failed: ${response.status} ${await response.text()}`)

  const status = await response.json() as {
    events_today?: number
    memory?: { topics?: number; profile?: number; timelineEvents?: number }
    recent_events?: unknown[]
  }

  if (typeof status.events_today !== "number") throw new Error("status missing events_today")
  if (typeof status.memory?.topics !== "number") throw new Error("status missing memory.topics")
  if (typeof status.memory?.profile !== "number") throw new Error("status missing memory.profile")
  if (typeof status.memory?.timelineEvents !== "number") throw new Error("status missing memory.timelineEvents")
  if (!Array.isArray(status.recent_events)) throw new Error("status missing recent_events")
}

async function waitForHealth(portNumber: number): Promise<void> {
  for (let attempt = 0; attempt < 20; attempt += 1) {
    try {
      const response = await fetch(`http://127.0.0.1:${portNumber}/health`)
      if (response.ok) return
    } catch {
      // Server is still starting.
    }
    await delay(100)
  }
  throw new Error("api server did not become healthy")
}

async function waitForMemoryPatch(tag: string): Promise<void> {
  for (let attempt = 0; attempt < 30; attempt += 1) {
    const event = queryOne<{ id: string }>(
      "SELECT id FROM events WHERE payload LIKE ? ORDER BY created_at DESC LIMIT 1",
      [`%${tag}%`]
    )
    const profile = queryOne<{ id: string }>(
      "SELECT id FROM profile WHERE key = ? AND value LIKE ?",
      ["last_mock_message", `%${tag}%`]
    )
    const topic = queryOne<{ id: string }>(
      "SELECT id FROM topics WHERE summary LIKE ?",
      ["%Generated by mock LLM provider%"]
    )
    const timeline = queryOne<{ id: string }>(
      "SELECT id FROM timeline_events WHERE summary LIKE ?",
      [`%${tag}%`]
    )

    if (event && profile && topic && timeline) return
    await delay(100)
  }
  throw new Error("memory patch was not written")
}

function cleanupSmokeRows(tag: string): void {
  run("DELETE FROM timeline_events WHERE summary LIKE ?", [`%${tag}%`])
  run("DELETE FROM profile WHERE key = ? AND value LIKE ?", ["last_mock_message", `%${tag}%`])
  run("DELETE FROM topics WHERE summary LIKE ?", ["%Generated by mock LLM provider%"])
  run("DELETE FROM events WHERE payload LIKE ?", [`%${tag}%`])
}
