const tag = `codex-memory-inspect-${Date.now()}`

const { initializeDb, run } = await import("../../infra/db/pool.js")
const {
  applyMemoryPatch,
  inspectMemory,
  inspectMemorySources,
  listMemoryProfile,
  listMemoryTimelineEvents,
  listMemoryTopics,
} = await import("./store.js")

initializeDb()

try {
  applyMemoryPatch({
    profile_updates: [
      {
        key: "inspection_test_profile",
        value: { tag, mode: "read-only" },
        confidence: 0.9,
      },
    ],
    topic_updates: [
      {
        name: tag,
        summary: "Generated by Memory inspection contract test.",
      },
    ],
    timeline_events: [
      {
        date: "2026-07-03",
        type: "insight",
        summary: `Memory inspection observed ${tag}`,
      },
      {
        date: "2026-07-04",
        type: "decision",
        summary: `Memory inspection normalized invalid timeline type ${tag}`,
      } as never,
    ],
  })

  const inspection = inspectMemory({ topicLimit: 20, profileLimit: 20, timelineLimit: 20 })
  const sourceInspection = inspectMemorySources()

  assert(typeof inspection.stats.topics === "number", "stats.topics must be number")
  assert(typeof inspection.stats.profile === "number", "stats.profile must be number")
  assert(typeof inspection.stats.timelineEvents === "number", "stats.timelineEvents must be number")
  assert(typeof sourceInspection.profileWithSource === "number", "profileWithSource must be number")
  assert(typeof sourceInspection.profileMissingSource === "number", "profileMissingSource must be number")
  assert(typeof sourceInspection.timelineWithSource === "number", "timelineWithSource must be number")
  assert(typeof sourceInspection.timelineMissingSource === "number", "timelineMissingSource must be number")

  const topic = inspection.topics.find((item) => item.name === tag)
  assert(topic, "inspection missing test topic")
  assert(topic.summary === "Generated by Memory inspection contract test.", "topic summary mismatch")
  assert(typeof topic.message_count === "number", "topic.message_count must be number")
  assert(listMemoryTopics({ name: tag, limit: 1 })[0]?.id === topic.id, "topic list filter mismatch")

  const profile = inspection.profile.find((item) => item.key === "inspection_test_profile")
  assert(profile, "inspection missing test profile")
  const profileValue = JSON.parse(profile.value) as { tag?: string; mode?: string }
  assert(profileValue.tag === tag, "profile value tag mismatch")
  assert(profileValue.mode === "read-only", "profile value mode mismatch")
  assert(listMemoryProfile({ key: "inspection_test_profile", limit: 1 })[0]?.id === profile.id, "profile list filter mismatch")

  const timeline = inspection.timelineEvents.find((item) => item.summary.startsWith("Memory inspection observed"))
  assert(timeline, "inspection missing test timeline event")
  assert(timeline.type === "insight", "timeline type mismatch")
  assert(listMemoryTimelineEvents({ type: "insight", date: "2026-07-03", limit: 100 }).some((item) => item.id === timeline.id), "timeline list filter mismatch")

  const normalizedTimeline = inspection.timelineEvents.find((item) => item.summary.includes("normalized invalid timeline type"))
  assert(normalizedTimeline, "inspection missing normalized timeline event")
  assert(normalizedTimeline.type === "insight", "invalid timeline type should normalize to insight")

  console.log("memory inspection ok")
} finally {
  cleanupRows(tag)
}

function cleanupRows(testTag: string): void {
  run("DELETE FROM timeline_events WHERE summary LIKE ?", [`%${testTag}%`])
  run("DELETE FROM profile WHERE key = ?", ["inspection_test_profile"])
  run("DELETE FROM topics WHERE name = ?", [testTag])
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message)
}

export {}
