const tag = `codex-memory-inspect-${Date.now()}`

const { initializeDb, run } = await import("../../infra/db/pool.js")
const {
  applyMemoryPatch,
  getMemoryContext,
  inspectMemory,
  inspectMemorySources,
  listMemoryProfile,
  listMemoryTimelineEvents,
  listMemoryTopics,
  updateProfileState,
  updateTopicState,
} = await import("./store.js")

initializeDb()

try {
  applyMemoryPatch({
    profile_updates: [
      {
        key: "inspection_test_profile",
        value: { tag, mode: "read-only" },
        confidence: 0.9,
      },
    ],
    topic_updates: [
      {
        name: tag,
        summary: "Generated by Memory inspection contract test.",
      },
    ],
    timeline_events: [
      {
        date: "2026-07-03",
        type: "insight",
        summary: `Memory inspection observed ${tag}`,
      },
      {
        date: "2026-07-04",
        type: "decision",
        summary: `Memory inspection normalized invalid timeline type ${tag}`,
      } as never,
    ],
  })

  const inspection = inspectMemory({ topicLimit: 20, profileLimit: 20, timelineLimit: 20 })
  const sourceInspection = inspectMemorySources()

  assert(typeof inspection.stats.topics === "number", "stats.topics must be number")
  assert(typeof inspection.stats.profile === "number", "stats.profile must be number")
  assert(typeof inspection.stats.timelineEvents === "number", "stats.timelineEvents must be number")
  assert(typeof sourceInspection.profileWithSource === "number", "profileWithSource must be number")
  assert(typeof sourceInspection.profileMissingSource === "number", "profileMissingSource must be number")
  assert(typeof sourceInspection.timelineWithSource === "number", "timelineWithSource must be number")
  assert(typeof sourceInspection.timelineMissingSource === "number", "timelineMissingSource must be number")

  const topic = inspection.topics.find((item) => item.name === tag)
  assert(topic, "inspection missing test topic")
  assert(topic.summary === "Generated by Memory inspection contract test.", "topic summary mismatch")
  assert(typeof topic.message_count === "number", "topic.message_count must be number")
  assert(listMemoryTopics({ name: tag, limit: 1 })[0]?.id === topic.id, "topic list filter mismatch")

  const profile = inspection.profile.find((item) => item.key === "inspection_test_profile")
  assert(profile, "inspection missing test profile")
  const profileValue = JSON.parse(profile.value) as { tag?: string; mode?: string }
  assert(profileValue.tag === tag, "profile value tag mismatch")
  assert(profileValue.mode === "read-only", "profile value mode mismatch")
  assert(listMemoryProfile({ key: "inspection_test_profile", limit: 1 })[0]?.id === profile.id, "profile list filter mismatch")

  const profileStateEventId = `${tag}-profile-state`
  const topicStateEventId = `${tag}-topic-state`
  run(
    `INSERT INTO events (id, source, type, payload, "timestamp", metadata)
     VALUES (?, 'system', 'memory_profile_suppression', ?, datetime('now'), ?)`,
    [profileStateEventId, JSON.stringify({ tag, target_id: profile.id }), JSON.stringify({ purpose: "memory_governance" })]
  )
  run(
    `INSERT INTO events (id, source, type, payload, "timestamp", metadata)
     VALUES (?, 'system', 'memory_topic_suppression', ?, datetime('now'), ?)`,
    [topicStateEventId, JSON.stringify({ tag, target_id: topic.id }), JSON.stringify({ purpose: "memory_governance" })]
  )

  const suppressedProfile = updateProfileState({
    id: profile.id,
    state: "suppressed",
    eventId: profileStateEventId,
    reason: "inspection suppression",
  })
  assert(suppressedProfile?.state === "suppressed", "profile suppression state mismatch")

  const archivedTopic = updateTopicState({
    id: topic.id,
    state: "archived",
    eventId: topicStateEventId,
    reason: "inspection archive",
  })
  assert(archivedTopic?.state === "archived", "topic archive state mismatch")

  const filteredContext = getMemoryContext({ topicLimit: 50, profileLimit: 50, timelineLimit: 50 })
  assert(!filteredContext.profile.some((item) => item.id === profile.id), "suppressed profile must not enter memory context")
  assert(!filteredContext.topics.some((item) => item.id === topic.id), "archived topic must not enter memory context")
  assert(!listMemoryProfile({ key: "inspection_test_profile", limit: 20 }).some((item) => item.id === profile.id), "suppressed profile must not enter default profile list")
  assert(listMemoryProfile({ key: "inspection_test_profile", state: "suppressed", limit: 20 }).some((item) => item.id === profile.id), "state=suppressed must include suppressed profile")
  assert(!listMemoryTopics({ name: tag, limit: 20 }).some((item) => item.id === topic.id), "archived topic must not enter default topic list")
  assert(listMemoryTopics({ name: tag, state: "archived", limit: 20 }).some((item) => item.id === topic.id), "state=archived must include archived topic")

  applyMemoryPatch({
    profile_updates: [
      {
        key: "inspection_test_profile",
        value: { tag, mode: "updated while suppressed" },
        confidence: 1,
      },
    ],
    topic_updates: [
      {
        name: tag,
        summary: "Updated while archived.",
      },
    ],
    timeline_events: [],
  })
  assert(listMemoryProfile({ key: "inspection_test_profile", state: "suppressed", limit: 20 }).some((item) => item.id === profile.id), "profile upsert must not revive suppressed profile")
  assert(listMemoryTopics({ name: tag, state: "archived", limit: 20 }).some((item) => item.id === topic.id), "topic upsert must not revive archived topic")

  const timeline = inspection.timelineEvents.find((item) => item.summary.startsWith("Memory inspection observed"))
  assert(timeline, "inspection missing test timeline event")
  assert(timeline.type === "insight", "timeline type mismatch")
  assert(listMemoryTimelineEvents({ type: "insight", date: "2026-07-03", limit: 100 }).some((item) => item.id === timeline.id), "timeline list filter mismatch")

  const normalizedTimeline = inspection.timelineEvents.find((item) => item.summary.includes("normalized invalid timeline type"))
  assert(normalizedTimeline, "inspection missing normalized timeline event")
  assert(normalizedTimeline.type === "insight", "invalid timeline type should normalize to insight")

  console.log("memory inspection ok")
} finally {
  cleanupRows(tag)
}

function cleanupRows(testTag: string): void {
  run("DELETE FROM timeline_events WHERE summary LIKE ?", [`%${testTag}%`])
  run("DELETE FROM profile WHERE key = ?", ["inspection_test_profile"])
  run("DELETE FROM topics WHERE name = ?", [testTag])
  run("DELETE FROM events WHERE payload LIKE ?", [`%${testTag}%`])
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message)
}

export {}
